-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGcgqf81qHqeC/fhH
CXOKr85as+Y8lPWU2JOfZABLX16gCgYIKoZIzj0DAQehRANCAARVoTTD2qh9cxaM
eTiDyj0bGEDfXFWJ/7uKJ9XlW/vqiR/JFGmZAVH3hAzEfSS7Y2nHI3arn7GbVMK5
AhBSJVgm
-----END PRIVATE KEY-----